### PR TITLE
Improved make install target for custom prefix

### PR DESCRIPTION
**Pull request by pbosetti**
Allows install on custom prefix with `make PREFIX=/opt/local install`.

### CODE REVIEW

**Comment by kroggen** [comment]
Great contribution!

What do you think of making it lowercase?

I checked many places on internet and it appears to be the default. Example:

https://stackoverflow.com/questions/29366974/in-a-makefile-do-we-use-prefix-or-prefix

**Comment by pbosetti** [comment]
As you prefer. I am used to lowercase in autotools/configure, and uppercase for configurable options in pure make, though. 
I am afraid I forgot to explain its use in Readme...

**Comment by pbosetti** [comment]
By the way, binn is lovely. I am adding it here: [xtemplate](https://github.com/pbosetti/xtemplate)

**Comment by kroggen** [comment]
> I am used to lowercase in autotools/configure, and uppercase for configurable options in pure make

Indeed, me too. But I guess we should use the default for this parameter.

Or to support both cases, if possible.

> By the way, binn is lovely. I am adding it here: xtemplate

Nice!

**Pull request merged**
